name: CI Checks
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v3
      
      - name: Встановлення залежностей
        run: npm install

      - name: Запуск авто-тестів
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v3
      
      - name: Встановлення ESLint
        run: npm install --save-dev eslint

      - name: Запуск перевірки стилю коду
        run: npx eslint . --max-warnings=0

  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v3

      - name: Запуск аналізу якості коду (SonarQube)
        run: sonar-scanner
